//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePoll_DataLayer
{
    using System;
    
    public partial class Answers_Header
    {
        public System.Guid AnswerHeaderId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string IpAddress { get; set; }
        public short TimeZoneId { get; set; }
        public bool IsDstTime { get; set; }
        public System.DateTime CreatedDateUtc { get; set; }
        public Nullable<int> UserAgentId { get; set; }
    }
}
