//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePoll_DataLayer
{
    using System;
    
    public partial class Poll
    {
        public System.Guid PollId { get; set; }
        public string PollName { get; set; }
        public string PollDescription { get; set; }
        public System.DateTime CreatedDateUtc { get; set; }
        public Nullable<byte> PageSize { get; set; }
        public Nullable<short> PageIndex { get; set; }
        public Nullable<int> PageTotal { get; set; }
    }
}
