//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePoll_DataLayer
{
    using System;
    
    public partial class Question
    {
        public System.Guid QuestionId { get; set; }
        public System.Guid PollId { get; set; }
        public string QuestionText { get; set; }
        public Nullable<decimal> QuestionValue { get; set; }
        public System.DateTime CreatedDateUtc { get; set; }
    }
}
